### ISSUE TITLE
error wen generating uuid

### ISSUE THREAD

**Issue by Manubi** [MariusRumpf/alfred-uuid#1]
Hi,
I used your workflow already on my old mac. It's awesome. But on the new one I get this error. 

[18:50:55.024] Generate UUID[Script Filter] Processing complete
[18:50:55.033] Generate UUID[Script Filter] Passing output 'uid v4' to Filter
[18:50:55.035] Generate UUID[Script Filter] Passing output 'uid v4' to Filter
[18:50:55.036] Generate UUID[Filter] Processing complete
[18:50:55.037] Generate UUID[Filter] Passing output 'uid v4' to Run Script
[18:50:55.245] ERROR: Generate UUID[Run Script] 31:39: syntax error: A “"” can’t go after this identifier. (-2740)

any ideas?

**Comment by imoby** [comment]
Getting the same error

**Comment by chrisspiegl** [comment]
Same here 👍

**Comment by johnzweng** [comment]
Hi! I'm getting the same error. Seems to originate in the "Run script" block: `tell application "Alfred 3" to search "{query}"`

I have not found out yet, what the problem is exactly, but as a **workaround**: Entering the full command (skipping the first "Generate v1" vs "Generate v4" menu selection) into Alfred seems to work:

Just enter directly:

- `uid v1` or:
- `uid v4`

**Comment by johnzweng** [comment]
The original error can be reproduced like this (in a terminal window):

```bash
john@macbook:~$ osascript -e 'tell application "Alfred 3" to search "uid v4"'
31:39: syntax error: A “"” can’t go after this identifier. (-2740)
```

**Comment by johnzweng** [comment]
🤦  of course, the Application name of Alfred is now `Alfred 4` and not `Alfred 3`.

So if you want to manually fix this, open the workflow, doubleclick the `/usr/bin/osascript` block and change the Script (change the digit `3` to `4`). Then it will work again.


**OLD:**
```
tell application "Alfred 3" to search "{query}"
```
**NEW:**
```
tell application "Alfred 4" to search "{query}"
```

## See also the screenshots:
![Screenshot 2020-09-10 at 07 01 42](https://user-images.githubusercontent.com/285900/92683784-1686bf80-f334-11ea-9457-5200876373cb.png)

![Screenshot 2020-09-10 at 07 07 01](https://user-images.githubusercontent.com/285900/92683849-4a61e500-f334-11ea-802c-05d468c09e31.png)

**Comment by chrisspiegl** [comment]
@johnzweng Thank you for this tip. Great idea.
Still would hope that the workflow get's an update, though, I don't know how one would make it so that it is compatible with both Alfred versions?

**Comment by chrisspiegl** [comment]
@MariusRumpf That's awesome. Just tested the workflow. Works great.
